default: &default

  # =================== DocuSign Config Area ===================

  BASE_URL: 'http://localhost:3000'
  DOCUSIGN_USERNAME: 'john.smith29324@gmail.com'
  DOCUSIGN_PASSWORD: 'password123'
  DOCUSIGN_INTEGRATION_KEY: '7c3457f0-5abb-49f7-97b8-5ad0c634eed9'
  DOCUSIGN_ACCOUNT_ID: '9cd1931b-622b-4ef4-ba22-734d795fa299'
  DOCUSIGN_USER_ID: '6c5dab3e-feee-4c2b-a32e-7b756b9e24cf'
  DOCUSIGN_ENDPOINT: 'http://demo.docusign.net/restapi'
  DOCUSIGN_API_VERSION: 'v2'
  DOCUSIGN_AUTH_SERVER: 'account-d.docusign.com'

  # JWT authentication link: https://account-d.docusign.com/oauth/auth?response_type=code&scope=impersonation&client_id=7c3457f0-5abb-49f7-97b8-5ad0c634eed9&redirect_uri=http://localhost:3000/ds_test_page

  # =================== DocuSign Config Area ===================
