default: &default

  
  APP_EMAIL: john.smith29324@gmail.com
  # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ DocuSign Config Area ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
  DOCUSIGN_USERNAME: john.smith29324@gmail.com
  DOCUSIGN_PASSWORD: password123
  DOCUSIGN_INTEGRATION_KEY: 7c3457f0-5abb-49f7-97b8-5ad0c634eed9
  DOCUSIGN_ACCOUNT_ID: 9cd1931b-622b-4ef4-ba22-734d795fa299
  DOCUSIGN_USER_ID: 6c5dab3e-feee-4c2b-a32e-7b756b9e24cf
  DOCUSIGN_ENDPOINT: http://demo.docusign.net/restapi
  DOCUSIGN_API_VERSION: v2
  DOCUSIGN_OAUTH_BASE_PATH: account-d.docusign.com
  DOCUSIGN_SCOPE: signature impersonation dtr.rooms.read dtr.rooms.write dtr.documents.read dtr.documents.write dtr.profile.read dtr.profile.write dtr.company.read dtr.company.write room_forms click.manage click.send organization_read group_read permission_read user_read user_write account_read domain_read identity_provider_read
  DOCUSIGN_AUTH_SERVER: https://account-d.docusign.com
  DOCUSIGN_REDIRECT_URI: #{Rails.configuration.URL_ROOT} /ds_test_page
  # ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑ DocuSign Config Area ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

development:
  <<: *default
  URL_ROOT: http://localhost:3000
  STRIPE_PUBLIC_KEY: pk_test_51KvBlgLjpnfKvSk6FTI71JbrjyOt2JiMNLhUqKR9dJDt4CvnhudKy1yP5zztbuLxsOKSQb9sBhvRLl5qGKpdWxJl00sjgbjMEp
  STRIPE_SECRET_KEY: sk_test_51KvBlgLjpnfKvSk6arxU2hPFxqFyUZ0n04tMySK7zGtaW6uMvyNYSu0hmFFvHWbVfSV5ktCwBpA9SqDURyzLAqB500eojmzBm3
  STRIPE_ENDPOINT_SECRET: whsec_289838b8cd69e734c788200ac5e50d50125c46c0ccaf6462f1d8ae355c043ce3
  PAYMENT_MINIMUM_IN_DOLLARS: 1
  PAYMENT_MAXIMUM_IN_DOLLARS: 100000

test:
  <<: *default
  URL_ROOT: http://localhost:3000
  STRIPE_PUBLIC_KEY: pk_test_51KvBlgLjpnfKvSk6FTI71JbrjyOt2JiMNLhUqKR9dJDt4CvnhudKy1yP5zztbuLxsOKSQb9sBhvRLl5qGKpdWxJl00sjgbjMEp
  STRIPE_SECRET_KEY: sk_test_51KvBlgLjpnfKvSk6arxU2hPFxqFyUZ0n04tMySK7zGtaW6uMvyNYSu0hmFFvHWbVfSV5ktCwBpA9SqDURyzLAqB500eojmzBm3
  STRIPE_ENDPOINT_SECRET: whsec_289838b8cd69e734c788200ac5e50d50125c46c0ccaf6462f1d8ae355c043ce3
  PAYMENT_MINIMUM_IN_DOLLARS: 1
  PAYMENT_MAXIMUM_IN_DOLLARS: 100000


production:
  <<: *default
  URL_ROOT: https://settlementdoneeasy.com
  STRIPE_PUBLIC_KEY: pk_test_51KvBlgLjpnfKvSk6FTI71JbrjyOt2JiMNLhUqKR9dJDt4CvnhudKy1yP5zztbuLxsOKSQb9sBhvRLl5qGKpdWxJl00sjgbjMEp
  STRIPE_SECRET_KEY: sk_test_51KvBlgLjpnfKvSk6arxU2hPFxqFyUZ0n04tMySK7zGtaW6uMvyNYSu0hmFFvHWbVfSV5ktCwBpA9SqDURyzLAqB500eojmzBm3
  STRIPE_ENDPOINT_SECRET: whsec_2gq7mq4B6Xy0g1cKe0KytCtfhTOFxqbX
  PAYMENT_MINIMUM_IN_DOLLARS: 1
  PAYMENT_MAXIMUM_IN_DOLLARS: 100000
