default: &default

  BASE_URL: http://localhost:3000
  APP_EMAIL: john.smith29324@gmail.com
  # =================== DocuSign Config Area ===================

  DOCUSIGN_USERNAME: john.smith29324@gmail.com
  DOCUSIGN_PASSWORD: password123
  DOCUSIGN_INTEGRATION_KEY: 7c3457f0-5abb-49f7-97b8-5ad0c634eed9
  DOCUSIGN_ACCOUNT_ID: 9cd1931b-622b-4ef4-ba22-734d795fa299
  DOCUSIGN_USER_ID: 6c5dab3e-feee-4c2b-a32e-7b756b9e24cf
  DOCUSIGN_ENDPOINT: http://demo.docusign.net/restapi
  DOCUSIGN_API_VERSION: v2
  DOCUSIGN_BASE_PATH: account-d.docusign.com
  DOCUSIGN_SCOPE: signature impersonation dtr.rooms.read dtr.rooms.write dtr.documents.read dtr.documents.write dtr.profile.read dtr.profile.write dtr.company.read dtr.company.write room_forms click.manage click.send organization_read group_read permission_read user_read user_write account_read domain_read identity_provider_read
  DOCUSIGN_AUTH_SERVER: https://account-d.docusign.com
  DOCUSIGN_REDIRECT_URI: http://localhost:3000/ds_test_page
  # =================== DocuSign Config Area ===================


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

  # JWT authentication link: https://account-d.docusign.com/oauth/auth?response_type=code&scope=impersonation&client_id=7c3457f0-5abb-49f7-97b8-5ad0c634eed9&redirect_uri=http://localhost:3000/ds_test_page

